
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=activitySelection_cce0da1981
ROOST_METHOD_SIG_HASH=activitySelection_79d2670611

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/java-report-test/1752137662/source/Java/src/test/java/com/thealgorithms/greedyalgorithms/ActivitySelectionTest.java
Tests:
    "@Test
@Test
public void testActivitySelection() {
    int[] start = { 1, 3, 0, 5, 8, 5 };
    int[] end = { 2, 4, 6, 7, 9, 9 };
    ArrayList<Integer> result = ActivitySelection.activitySelection(start, end);
    ArrayList<Integer> expected = new ArrayList<>(Arrays.asList(0, 1, 3, 4));
    assertEquals(expected, result);
}
"
    "@Test
@Test
public void testSingleActivity() {
    int[] start = { 1 };
    int[] end = { 2 };
    ArrayList<Integer> result = ActivitySelection.activitySelection(start, end);
    ArrayList<Integer> expected = new ArrayList<>(Arrays.asList(0));
    assertEquals(expected, result);
}
"
    "@Test
@Test
public void testNoOverlap() {
    int[] start = { 1, 2, 3 };
    int[] end = { 2, 3, 4 };
    ArrayList<Integer> result = ActivitySelection.activitySelection(start, end);
    ArrayList<Integer> expected = new ArrayList<>(Arrays.asList(0, 1, 2));
    assertEquals(expected, result);
}
"
Scenario 1: Test method with completely overlapping activities

Details:
  TestName: testCompletelyOverlappingActivities
  Description: Verify the behavior of the method when all activities have overlapping start and end times, ensuring only the first activity is selected.

Execution:
  Arrange: Set up arrays `startTimes` and `endTimes` where all activities overlap.
  Act: Call the `activitySelection` method with the prepared arrays.
  Assert: Verify that the result contains only the index of the first activity and none of the others.

Validation:
  This test validates that the algorithm correctly selects only one activity when all activities overlap and no subsequent activities can be scheduled. It ensures the correctness of logic for overlapping scenarios in real-world applications like scheduling.

*/

// ********RoostGPT********

package com.thealgorithms.greedyalgorithms;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.assertj.core.api.Assertions.assertThat;
import java.util.ArrayList;
import org.junit.jupiter.api.*;
import java.util.Arrays;
import java.util.Comparator;

class ActivitySelectionActivitySelectionTest {

	@Tag("valid")
	@Test
	public void testCompletelyOverlappingActivities() {
		// Arrange
		int[] startTimes = { 1, 1, 1 };
		int[] endTimes = { 2, 2, 2 };
		// Act
		ArrayList<Integer> result = ActivitySelection.activitySelection(startTimes, endTimes);
		// Assert
		assertThat(result).isNotNull();
		assertThat(result.size()).isEqualTo(1); // First activity only
		assertThat(result.get(0)).isEqualTo(0);
	}

	@Tag("boundary")
	@Test
	public void testSingleActivity() {
		// Arrange
		int[] startTimes = { 1 };
		int[] endTimes = { 2 };
		// Act
		ArrayList<Integer> result = ActivitySelection.activitySelection(startTimes, endTimes);
		// Assert
		assertThat(result).isNotNull();
		assertThat(result.size()).isEqualTo(1);
		assertThat(result.get(0)).isEqualTo(0);
	}

	@Tag("valid")
	@Test
	public void testNonOverlappingActivities() {
		// Arrange
		int[] startTimes = { 1, 3, 5 };
		int[] endTimes = { 2, 4, 6 };
		// Act
		ArrayList<Integer> result = ActivitySelection.activitySelection(startTimes, endTimes);
		// Assert
		assertThat(result).isNotNull();
		assertThat(result.size()).isEqualTo(3); // All activities are selected
		assertThat(result.get(0)).isEqualTo(0);
		assertThat(result.get(1)).isEqualTo(1);
		assertThat(result.get(2)).isEqualTo(2);
	}

	@Tag("valid")
	@Test
	public void testPartialOverlappingActivities() {
		// Arrange
		int[] startTimes = { 1, 2, 3 };
		int[] endTimes = { 3, 4, 5 };
		// Act
		ArrayList<Integer> result = ActivitySelection.activitySelection(startTimes, endTimes);
		// Assert
		assertThat(result).isNotNull();
		assertThat(result.size()).isEqualTo(2);
		assertThat(result.get(0)).isEqualTo(0);
		assertThat(result.get(1)).isEqualTo(2);
	}

	@Tag("invalid")
	@Test
	public void testEmptyActivities() {
		// Arrange
		int[] startTimes = {};
		int[] endTimes = {};
		// Act
		ArrayList<Integer> result = ActivitySelection.activitySelection(startTimes, endTimes);
		// Assert
		assertThat(result).isNotNull();
		assertThat(result.size()).isEqualTo(0); // No activities selected
	}

}