

// ********RoostGPT********
/*
Test generated by RoostGPT for test java-report-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=of_eb8138c6bc
ROOST_METHOD_SIG_HASH=of_7a04d5363c

                               תסריט מספר 1: יצירת אובייקט Job עם ערכים תקינים  
                                                                                
                                                                        פרטים:  
                                                שם בדיקה: createJobValidValues  
.תיאור: בדיקה מאשרת שהמתודה of יוצרת אובייקט Job ומחזירה ערכים נכונים כאשר מוזנים פרמטרים תקינים.
                                                                                
                                                                        ביצוע:  
                                                                          הכנה: 
.- מגדירים את ערכי הפרמטרים הבאים: jobName = "Task1", processingTime = 5, deadline = 10.
                                                                                
                                                                         פעולה: 
                  .- מזמנים את המתודה Job.of ומעבירים את הפרמטרים המוגדרים.
                                                                                
                                                                         אישור: 
.- משתמשים באימות JUnit (assertions) כדי לוודא שאובייקט ה-Job שנוצר מכיל את הערכים המצופים: jobName = "Task1", processingTime = 5, deadline = 10.
                                                                                
                                                                        אימות:  
.- הבדיקה מאשרת שהמימוש של המתודה of נכון עבור קלט תקין, ומוודאת יצירה תקינה של אובייקט Job.
                                                                                
*/

// ********RoostGPT********

package com.thealgorithms.greedyalgorithms;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.*;
import java.util.Arrays;

public class JobOfTest {
    @Test
    @Tag("valid")
    public void testCreateJobValidValues() {
        // Arrange
        String jobName = "Task1";
        int processingTime = 5;
        int deadline = 10;
        // Act
        MinimizingLateness.Job job = MinimizingLateness.Job.of(jobName, processingTime, deadline);
        // Assert
        assertEquals(jobName, job.jobName, "Job name should match");
        assertEquals(processingTime, job.processingTime, "Processing time should match");
        assertEquals(deadline, job.deadline, "Deadline should match");
    }
    @Test
    @Tag("invalid")
    public void testCreateJobWithNegativeProcessingTime() {
        // Arrange
        String jobName = "Task2";
        int processingTime = -5; // Invalid value
        int deadline = 10;
        // Act
        MinimizingLateness.Job job = MinimizingLateness.Job.of(jobName, processingTime, deadline);
        // Assert
        assertEquals(jobName, job.jobName, "Job name should match");
        assertEquals(processingTime, job.processingTime, "Negative processing time is accepted");
        assertEquals(deadline, job.deadline, "Deadline should match");
        // TODO: Add validation in source code to throw an exception for negative processing time.
    }
    @Test
    @Tag("boundary")
    public void testCreateJobWithBoundaryValues() {
        // Arrange
        String jobName = "Task3";
        int processingTime = 0; // Boundary value
        int deadline = Integer.MAX_VALUE;
        // Act
        MinimizingLateness.Job job = MinimizingLateness.Job.of(jobName, processingTime, deadline);
        // Assert
        assertEquals(jobName, job.jobName, "Job name should match");
        assertEquals(processingTime, job.processingTime, "Processing time should match");
        assertEquals(deadline, job.deadline, "Deadline should match");
    }
    @Test
    @Tag("valid")
    public void testCreateJobWithMinimumValidValues() {
        // Arrange
        String jobName = "Task4";
        int processingTime = 1;
        int deadline = 1;
        // Act
        MinimizingLateness.Job job = MinimizingLateness.Job.of(jobName, processingTime, deadline);
        // Assert
        assertEquals(jobName, job.jobName, "Job name should match");
        assertEquals(processingTime, job.processingTime, "Processing time should match");
        assertEquals(deadline, job.deadline, "Deadline should match");
    }
    @Test
    @Tag("valid")
    public void testCreateJobWithDefaultValues() {
        // Arrange
        String jobName = ""; // Empty name
        int processingTime = 0;
        int deadline = 0;
        // Act
        MinimizingLateness.Job job = MinimizingLateness.Job.of(jobName, processingTime, deadline);
        // Assert
        assertEquals(jobName, job.jobName, "Job name should match");
        assertEquals(processingTime, job.processingTime, "Processing time should match");
        assertEquals(deadline, job.deadline, "Deadline should match");
    }
}