
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-customannotation-test using AI Type  and AI Model

ROOST_METHOD_HASH=of_eb8138c6bc
ROOST_METHOD_SIG_HASH=of_7a04d5363c

**Scenario 1: Valid Job Creation**

Details:
TestName: createValidJobWithAllArgsConstructor
Description: This test verifies that the `of` method correctly constructs a new Job object with valid arguments provided (non-null job name and non-negative integers for processing time and deadline).
Execution:
  - Arrange: Declare necessary job name, processing time, and deadline parameters for a job.
  - Act: Call the `of` method using the arranged parameters.
  - Assert: Assert that the returned Job object is not null, check that properties of the job match the input parameters.
Validation:
  - The assertion checks that the Job object is properly instantiated and properties are accurately assigned. This is significant for ensuring data is correctly passed to the object and stored, impacting how Job objects behave and are processed within the application.

**Scenario 2: Job Creation With Null Job Name**

Details:
TestName: createJobWithNullName
Description: This test checks that the `of` method handles the case where a null jobName is passed. Depending upon the unspecified handling of the constructor, it might either accept the null or throw an IllegalArgumentException.
Execution:
  - Arrange: Set jobName to null, and define valid processing time and deadline.
  - Act: Call the `of` method using these parameters and catch any exceptions if thrown.
  - Assert: Assert either no exception and a null job name in the Job object, or an IllegalArgumentException depending on the defined behavior of the constructor.
Validation:
  - Validate how the system behaves with incomplete data inputs (null values). Ensuring robust handling of such cases protects the system from unintended behaviors or crashes.

**Scenario 3: Negative Processing Time**

Details:
TestName: createJobWithNegativeProcessingTime
Description: This scenario tests the behavior of the `of` method when a negative processing time is provided, which may not be logically valid.
Execution:
  - Arrange: Provide a valid jobName, negative processing time, and a valid deadline.
  - Act: Call the `of` method with these parameters and catch any exceptions if expected.
  - Assert: Assert either correct exception throwing such as IllegalArgumentException or check how negative values are handled.
Validation:
  - Validate that the `of` method handles or restricts invalid numeric input (negative values), ensuring data integrity and avoiding logical errors in job processing calculations.

**Scenario 4: Negative Deadline**

Details:
TestName: createJobWithNegativeDeadline
Description: This test assesses how the `of` method handles a job creation request with a negative deadline, potentially an operationally invalid scenario.
Execution:
  - Arrange: Provide a valid jobName, valid processing time, and a negative deadline.
  - Act: Call the `of` method with these parameters.
  - Assert: Checks if the deadline is handled as expected, either treated as an acceptable value or throwing an exception depending on the business logic.
Validation:
  - By checking this, we ensure that job scheduling logic that might depend on deadlines operates on valid data, critical for maintaining system operations' accuracy and reliability.

These scenarios check the robustness and correctness of the `of` method in creating Job objects, considering various edge cases and normal operating conditions.
*/

// ********RoostGPT********

package com.thealgorithms.greedyalgorithms;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import com.thealgorithms.greedyalgorithms.MinimizingLateness.Job;
import org.junit.jupiter.api.*;
import java.util.Arrays;

public class MinimizingLatenessJobOfTest {

	@Test
	@Tag("valid")
	public void createValidJobWithAllArgsConstructor() {
		// Arrange
		String jobName = "TestJob";
		int processingTime = 5;
		int deadline = 10;
		// Act
		Job job = Job.of(jobName, processingTime, deadline);
		// Assert
		assertNotNull(job);
		assertEquals(jobName, job.jobName);
		assertEquals(processingTime, job.processingTime);
		assertEquals(deadline, job.deadline);
	}

	@Test
	@Tag("invalid")
	public void createJobWithNullName() {
		// Arrange
		String jobName = null;
		int processingTime = 5;
		int deadline = 10;
		// Act & Assert
		Exception exception = assertThrows(IllegalArgumentException.class, () -> {
			Job.of(jobName, processingTime, deadline);
		});
		assertEquals("Job name cannot be null", exception.getMessage());
	}

	@Test
	@Tag("boundary")
	public void createJobWithNegativeProcessingTime() {
		// Arrange
		String jobName = "TestJob";
		int processingTime = -1;
		int deadline = 10;
		// Act & Assert
		Exception exception = assertThrows(IllegalArgumentException.class, () -> {
			Job.of(jobName, processingTime, deadline);
		});
		assertEquals("Processing time cannot be negative", exception.getMessage());
	}

	@Test
	@Tag("boundary")
	public void createJobWithNegativeDeadline() {
		// Arrange
		String jobName = "TestJob";
		int processingTime = 5;
		int deadline = -1;
		// Act & Assert
		Exception exception = assertThrows(IllegalArgumentException.class, () -> {
			Job.of(jobName, processingTime, deadline);
		});
		assertEquals("Deadline cannot be negative", exception.getMessage());
	}

}