
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-customannotation-test using AI Type  and AI Model

ROOST_METHOD_HASH=toString_7033209074
ROOST_METHOD_SIG_HASH=toString_bbffdadaa2

### Scenario 1: Verify Correct Format Representation of Job Information

**Details:**
- TestName: testToStringValidRepresentation
- Description: This test checks that the `toString()` method returns a string in the correct format as specified, including all job attributes such as jobName, startTime, endTime, and lateness.

**Execution:**
- Arrange: Create an instance of Job using the static factory method `Job.of("Job1", 4, 10)` with predefined values.
- Act: Call the `toString()` method on the created Job instance.
- Assert: Assert that the returned String matches the expected format and content: `"Job1, startTime: 0, endTime: 4, lateness: -6"`.

**Validation:**
- The assertion checks if the string representation includes the job's name, correctly calculated startTime as 0 (assuming an initial startTime of zero), endTime computed as the start time plus processing time, and the lateness calculated as the difference between endTime and deadline. This validates the accuracy and reliability of the Job representation in logs or outputs, ensuring alignment with business logic and debugging needs.

### Scenario 2: Verify String Output for Late Job

**Details:**
- TestName: testToStringWithLateness
- Description: Tests the `toString()` method for a job that completes after its deadline to ensure that lateness is correctly calculated and represented.

**Execution:**
- Arrange: Create a Job instance using `Job.of("Job2", 5, 3)` where the processing time leads to completion after the deadline.
- Act: Call the `toString()` method on the created Job instance.
- Assert: Assert that the string returned matches `"Job2, startTime: 0, endTime: 5, lateness: 2"` indicating a positive lateness value.

**Validation:**
- This test verifies that the method correctly handles and represents job instances where the deadline is missed. Positive lateness indicates a delay beyond the given deadline. This scenario is significant for managing scheduling expectations and assessing performance penalties.

### Scenario 3: Job Completes Exactly at Deadline

**Details:**
- TestName: testToStringEdgeCaseExactDeadline
- Description: Validates the `toString()` method output for a job that finishes exactly at its deadline time, resulting in zero lateness.

**Execution:**
- Arrange: Create a Job instance via the factory method `Job.of("Job3", 6, 6)`.
- Act: Call the `toString()` method.
- Assert: Assert the output to be `"Job3, startTime: 0, endTime: 6, lateness: 0"`.

**Validation:**
- The test ensures the method's correctness in scenarios where job processing time aligns exactly with the given deadline, yielding zero lateness. This test is crucial for confirming behavior at boundary conditions, which commonly occur in real-world scenarios and affect system performance and scheduling accuracy.

### Scenario 4: Job with Negative Lateness

**Details:**
- TestName: testToStringEarlyFinish
- Description: Checks the `toString()` output for a job that finishes before the deadline, showcasing negative lateness.

**Execution:**
- Arrange: Initialize a Job object with `Job.of("Job4", 2, 5)`.
- Act: Call the `toString()` method.
- Assert: Assert that the result matches `"Job4, startTime: 0, endTime: 2, lateness: -3"`.

**Validation:**
- This test confirms the method's capability to handle and accurately represent situations where jobs finish ahead of schedule. Negative lateness values are significant in scenarios assessing efficiency and early completion benefits, and such representation must be accurate and reliable in system logs or outputs for proper tracking and management of job schedules.
*/

// ********RoostGPT********

package com.thealgorithms.greedyalgorithms;

import java.util.Arrays;
import com.thealgorithms.greedyalgorithms.MinimizingLateness.Job;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.*;

public class MinimizingLatenessJobToStringTest {

	@Test
	@Tag("valid")
	public void testToStringValidRepresentation() {
		Job job = Job.of("Job1", 4, 10);
		String expected = "Job1, startTime: 0, endTime: 4, lateness: -6";
		assertEquals(expected, job.toString());
	}

	@Test
	@Tag("boundary")
	public void testToStringWithLateness() {
		Job job = Job.of("Job2", 5, 3);
		String expected = "Job2, startTime: 0, endTime: 5, lateness: 2";
		assertEquals(expected, job.toString());
	}

	@Test
	@Tag("boundary")
	public void testToStringEdgeCaseExactDeadline() {
		Job job = Job.of("Job3", 6, 6);
		String expected = "Job3, startTime: 0, endTime: 6, lateness: 0";
		assertEquals(expected, job.toString());
	}

	@Test
	@Tag("valid")
	public void testToStringEarlyFinish() {
		Job job = Job.of("Job4", 2, 5);
		String expected = "Job4, startTime: 0, endTime: 2, lateness: -3";
		assertEquals(expected, job.toString());
	}

}