# ********RoostGPT********

# Test generated by RoostGPT for test java-unit-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country_post for http method type POST 
# RoostTestHash=b16b61c2ee
# 
# 

# ********RoostGPT********
Feature: Country API Integration Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Create a new country successfully
    Given path 'country'
    And request
      """
      {
        "name": "<name>",
        "code": "<code>",
        "currencies": <currencies>,
        "default_currency": "<default_currency>",
        "is_active": <is_active>
      }
      """
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    When method POST
    Then status 201
    And match response.status == 'success'
    And match response.message == 'Country created successfully'
    And match response.data.id == '#number'
    And match response.data.name == '##string'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#string'
    And match response.data.updated_at == '#string'
    And match response.data.currencies == '#[]'
    And match response.data.currencies contains ['<currency_values>']

    Examples:
      | read('country_post.csv') |

  Scenario: Attempt to create a country with missing required headers
    Given path 'country'
    And request
      """
      {
        "name": "Canada",
        "code": "CAN",
        "currencies": ["CAD", "USD"],
        "default_currency": "CAD",
        "is_active": 1
      }
      """
    When method POST
    Then status != 201
    And match response.error.code == '#number'
    And match response.error.message == '#string'

  Scenario: Validate error handling for invalid request body attributes
    Given path 'country'
    And request
      """
      {
        "name": 1234,
        "code": null,
        "currencies": "Invalid",
        "default_currency": 5678,
        "is_active": "true"
      }
      """
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    When method POST
    Then status != 201
    And match response.error.code == '#number'
    And match response.error.message == '#string'

  Scenario Outline: Check the presence of required headers in responses
    Given path 'country'
    And request
      """
      {
        "name": "<name>",
        "code": "<code>",
        "currencies": <currencies>,
        "default_currency": "<default_currency>",
        "is_active": <is_active>
      }
      """
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    When method POST
    Then status 201
    And assert responseHeaders != null
    And assert karate.sizeOf(responseHeaders) >= 3

    Examples:
      | read('country_post.csv') |
