# ********RoostGPT********

# Test generated by RoostGPT for test java-unit-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country_get for http method type GET 
# RoostTestHash=3d9e7cb5d1
# 
# 

# ********RoostGPT********
Feature: Verify the functionality of Get all countries API endpoint

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { app_identifier: '{{processEnvironment.APP_IDENTIFIER}}', customer_secret_key: '{{processEnvironment.CUSTOMER_SECRET_KEY}}', Accept: 'application/json' }

  Scenario: Verify response code and body for valid request
    Given path 'country'
    When method GET
    Then status 200
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data.countries == '#array'
    And match each response.data.countries[*].id == '#number'
    And match each response.data.countries[*].name == '#? _ == null || typeof _ == "string"'
    And match each response.data.countries[*].code == '#string'
    And match each response.data.countries[*].default_currency == '#string'
    And match each response.data.countries[*].is_active == '#number'
    And match each response.data.countries[*].app_id == '#number'
    And match each response.data.countries[*].customer_id == '#number'
    And match each response.data.countries[*].created_by == '#number'
    And match each response.data.countries[*].updated_by == '#number'
    And match each response.data.countries[*].created_at == '#string'
    And match each response.data.countries[*].updated_at == '#string'
    And match each response.data.countries[*].currencies == '#array'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

  Scenario Outline: Verify response with different configurations
    Given path 'country'
    When method GET
    Then status <status_code>
    And match response.status == <status_type>
    And match response.message == <message_type>
    And match response.data.countries == '#array'
    And match each response.data.countries[*].id == '#number'
    And match each response.data.countries[*].name == '#? _ == null || typeof _ == "string"'
    And match each response.data.countries[*].code == '#string'
    And match each response.data.countries[*].default_currency == '#string'
    And match each response.data.countries[*].is_active == '#number'
    And match each response.data.countries[*].app_id == '#number'
    And match each response.data.countries[*].customer_id == '#number'
    And match each response.data.countries[*].created_by == '#number'
    And match each response.data.countries[*].updated_by == '#number'
    And match each response.data.countries[*].created_at == '#string'
    And match each response.data.countries[*].updated_at == '#string'
    And match each response.data.countries[*].currencies == '#array'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | status_code | status_type | message_type |
      |         200 | '#string'   | '#string'    |
