# ********RoostGPT********

# Test generated by RoostGPT for test java-unit-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_delete for http method type DELETE 
# RoostTestHash=5c040001f7
# 
# 

# ********RoostGPT********
Feature: Delete Country by ID API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Verify successful deletion of country by ID
    Given path '/country/', <id>
    And header Accept = 'application/json'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    When method DELETE
    Then status 200
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'
    And match response.message == 'Country deleted successfully'

    Examples:
      | read('country_id_delete.csv') |

  Scenario Outline: Verify invalid request due to missing ID parameter
    Given path '/country/', <id>
    And header Accept = 'application/json'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    When method DELETE
    Then assert responseStatus != 200
    And match response.error == '#string'
    And match response.error.code == '#string'
    And match response.error.message == '#string'

    Examples:
      | id |
      |    |

  Scenario: Verify response headers
    Given path '/country/32'
    And header Accept = 'application/json'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    When method DELETE
    Then status 200
    And match responseHeaders['Content-Type'] == 'application/json'
    And match responseHeaders['Transfer-Encoding'] == '#string'

  Scenario Outline: Verify error response structure for unauthorized key
    Given path '/country/', <id>
    And header Accept = 'application/json'
    And header app-identifier = 'invalid-value'
    And header customer-secret-key = 'invalid-value'
    When method DELETE
    Then assert responseStatus != 200
    And match response.error.code == '#string'
    And match response.error.message == '#string'

    Examples:
      | id |
      | 32 |
