# ********RoostGPT********

# Test generated by RoostGPT for test java-unit-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_put for http method type PUT 
# RoostTestHash=e5eb5af926
# 
# 

# ********RoostGPT********
Feature: Update Country by ID

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Successfully Update Country
    Given path 'country/{id}'
    And param id = <id>
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    And request
      """
      {
        "name": "<name>",
        "code": "<code>",
        "currencies": <currencies>,
        "default_currency": "<default_currency>",
        "is_active": <is_active>
      }
      """
    When method PUT
    Then status 200
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data.id == '#number'
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#string'
    And match response.data.updated_at == '#string'
    And match response.data.currencies == '#[]'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_id_put.csv') |

  Scenario: Invalid Country ID
    Given path 'country/{id}'
    And param id = 99999999
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    And request
      """
      {
        "name": "USA",
        "code": "USA",
        "currencies": ["USD", "EUR"],
        "default_currency": "USD",
        "is_active": 1
      }
      """
    When method PUT
    Then status != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'

  Scenario: Missing Required Header
    Given path 'country/{id}'
    And param id = 32
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    And request
      """
      {
        "name": "USA",
        "code": "USA",
        "currencies": ["USD", "EUR"],
        "default_currency": "USD",
        "is_active": 1
      }
      """
    When method PUT
    Then status != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'

  Scenario: Invalid Request Body Format
    Given path 'country/{id}'
    And param id = 32
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    And request
      """
      {
        "name": 12345,
        "code": true,
        "currencies": {},
        "default_currency": null,
        "is_active": "active"
      }
      """
    When method PUT
    Then status != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'
