# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=ff433d7857
# 
# 

# ********RoostGPT********
Feature: Testing Laureates API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Validate successful response with various query parameters
    Given path '2.1/laureates'
    And param offset = <offset>
    And param limit = <limit>
    And param gender = <gender>
    And param birthDate = <birthDate>
    When method GET
    Then status 200
    And match response.laureates == '#[]'

    Examples:
      | read('laureates_get.csv') |

  Scenario Outline: Validate response for invalid query parameters
    Given path '2.1/laureates'
    And param birthDate = <birthDate>
    When method GET
    Then status 400
    And match response.code == "404"
    And match response.message == '#string'

    Examples:
      | birthDate    |
      | "invalid"    |
      | "1234-99-00" |

  Scenario Outline: Validate response for not found resource
    Given path '2.1/laureates'
    And param ID = <ID>
    When method GET
    Then status 404
    And match response.code == "404"
    And match response.message == '#string'

    Examples:
      | ID  |
      | 999 |

  Scenario Outline: Validate response for unprocessable entity
    Given path '2.1/laureates'
    And param nobelPrizeYear = <nobelPrizeYear>
    And param yearTo = <yearTo>
    When method GET
    Then status 422
    And match response.code == "404"
    And match response.message == '#string'

    Examples:
      | nobelPrizeYear | yearTo |
      |           1980 |   1970 |

  Scenario Outline: Validate full response structure for success case
    Given path '2.1/laureates'
    And param limit = 1
    When method GET
    Then status 200
    And match response.laureates[0].id == '#number'
    And match response.laureates[0].laureateIfPerson.knownName.en == '#string'
    And match response.laureates[0].laureateIfPerson.birth.date == '''#regex ^[0-9]{4}-[0-9]{2}-[0-9]{2}'''
    And match response.laureates[0].laureateIfPerson.birth.place.city.en == '#string'
    And match response.laureates[0].laureateIfPerson.birth.place.country.se == '#string'
    And match response.laureates[0].laureateIfPerson.gender == '#string'
    And match response.laureates[0].nobelPrizes[0].awardYear == '#number'
    And match response.laureates[0].nobelPrizes[0].category.en == '#string'

  Scenario: Validate response headers
    Given path '2.1/laureates'
    When method GET
    Then status 200
    And match responseHeaders['Content-Type'] == "application/json"
