# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=e702c0f931
# 
# 

# ********RoostGPT********
Feature: API Tests for Nobel Prize Laureate Information

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Get laureate information by ID with valid ID
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 200
    And match response.laureate.id == '#number'
    And match response.laureate.laureateIfPerson == """ #? 
      response.laureate.laureateIfPerson == null || 
      response.laureate.laureateIfPerson == #object """
    And match response.laureate.laureateIfOrg == """ #? 
      response.laureate.laureateIfOrg == null || 
      response.laureate.laureateIfOrg == #object """
    And match response.laureate.wikidata.id == '#string'
    And match response.laureate.wikidata.url == '#string'
    And match response.laureate.wikipedia.slug == '#string'
    And match response.laureate.wikipedia.english == '#string'
    And match response.laureate.sameAs == '#array'
    And match response.laureate.nobelPrizes == '#array'
    And match each response.laureate.nobelPrizes[*].awardYear == '#number'
    And match each response.laureate.nobelPrizes[*].prizeAmount == '#number'
    And match each response.laureate.nobelPrizes[*].prizeStatus == '#string'
    And match response.laureate.links == '#array'

    Examples:
      | laureateID |
      | 456        |
      | 123        |

  Scenario Outline: Get laureate information by invalid ID (Bad Request)
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 400
    And match response.code == '404'
    And match response.message == """ #string """

    Examples:
      | laureateID |
      | -1         |
      | 0          |

  Scenario Outline: Get laureate information with non-existent ID (Not Found)
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 404
    And match response.code == '404'
    And match response.message == """ #string """

    Examples:
      | laureateID |
      | 999999     |
      | 888888     |

  Scenario Outline: Get laureate information returns Unprocessable Entity
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 422
    And match response.code == '422'
    And match response.message == """ #string """

    Examples:
      | laureateID |
      | null       |
      | abc        |
