# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API Test
  Perform API testing for the "/2.1/nobelPrizes" endpoint.

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Valid GET request with query parameters
    Given path '/2.1/nobelPrizes'
    And param offset = <offset>
    And param limit = <limit>
    And param sort = <sort>
    And param nobelPrizeYear = <nobelPrizeYear>
    And param yearTo = <yearTo>
    And param nobelPrizeCategory = <nobelPrizeCategory>
    And param format = <format>
    And param csvLang = <csvLang>
    When method GET
    Then status 200
    And match response == '#object'
    And match response.nobelPrizes == '#[]'
    And match response.meta.offset == '#number'
    And match response.meta.limit == '#number'
    And match response.meta.count == '#number'
    And match response.meta.nobelPrizeYear == '#number'
    And match response.meta.yearTo == '#number?'
    And match response.meta.nobelPrizeCategory == '#string?'
    And match response.links.first == '#string?'
    And match response.links.prev == '#string?'
    And match response.links.self == '#string?'
    And match response.links.next == '#string?'
    And match response.links.last == '#string?'
    And match each response.nobelPrizes[*].awardYear == '#number'
    And match each response.nobelPrizes[*].category.en == '#string'
    And match each response.nobelPrizes[*].category.se == '#string?'
    And match each response.nobelPrizes[*].dateAwarded == '#string'
    And match each response.nobelPrizes[*].prizeAmount == '#number'
    And match each response.nobelPrizes[*].prizeAmountAdjusted == '#number'
    And match each response.nobelPrizes[*].topMotivation.en == '#string'
    And match each response.nobelPrizes[*].laureates[*].id == '#number'
    And match each response.nobelPrizes[*].laureates[*].name.en == '#string'
    And match each response.nobelPrizes[*].laureates[*].portion == '#string'
    And match each response.nobelPrizes[*].laureates[*].sortOrder == '#string'
    And match each response.nobelPrizes[*].laureates[*].links[*].rel == '#string'
    And match each response.nobelPrizes[*].laureates[*].links[*].href == '#string'
    And match each response.nobelPrizes[*].laureates[*].links[*].action == '#string'
    And match each response.nobelPrizes[*].laureates[*].links[*].types == '#string'

    Examples:
      | read('nobelPrizes_get.csv') |

  Scenario: Invalid request with malformed parameters
    Given path '/2.1/nobelPrizes'
    And param offset = -1
    And param limit = -10
    When method GET
    Then status 400
    And match response == '#object'
    And match response.code == '404'
    And match response.message == '#string'

  Scenario: Resource not found
    Given path '/2.1/nobelPrizes'
    And param nobelPrizeYear = 1888
    When method GET
    Then status 404
    And match response == '#object'
    And match response.code == '404'
    And match response.message == '#string'

  Scenario: Unprocessable request
    Given path '/2.1/nobelPrizes'
    And param offset = 1
    And param limit = 10
    And param nobelPrizeCategory = unknown
    When method GET
    Then status 422
    And match response == '#object'
    And match response.code == '404'
    And match response.message == '#string'
