# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Tests for Nobel Prize API Endpoint /2.1/nobelPrize/{category}/{year}

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Validate successful retrieval of Nobel Prize details
    Given path '2.1', 'nobelPrize', <category>, <year>
    When method GET
    Then status 200
    And match response.nobelPrize.awardYear == '#number'
    And match response.nobelPrize.category.en == '#string'
    And match response.nobelPrize.category.se == '#string'
    And match response.nobelPrize.categoryFullName.en == '#string'
    And match response.nobelPrize.categoryFullName.se == '#string'
    And match response.nobelPrize.dateAwarded == '#regex ^\\d{4}-\\d{2}-\\d{2}$'
    And match response.nobelPrize.prizeAmount == '#number'
    And match response.nobelPrize.prizeAmountAdjusted == '#number'
    And match response.nobelPrize.topMotivation.en == '#string'
    And match response.nobelPrize.topMotivation.se == '#string'
    And match response.nobelPrize.laureates == '#array'
    And match response.nobelPrize.laureates[*].id == '#number'
    And match response.nobelPrize.laureates[*].name.en == '#string'
    And match response.nobelPrize.laureates[*].portion == '#string'
    And match response.nobelPrize.laureates[*].sortOrder == '#string'
    And match response.nobelPrize.laureates[*].motivation.en == '#string'
    And match response.nobelPrize.laureates[*].links[*].rel == '#string'
    And match response.nobelPrize.laureates[*].links[*].href == '#string'
    And match response.nobelPrize.laureates[*].links[*].action == '#string'

    Examples:
      | read('nobelPrize_category_year_get.csv') |

  Scenario Outline: Validate 400 Bad Request responses
    Given path '2.1', 'nobelPrize', <category>, <year>
    When method GET
    Then status 400
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | category  | year |
      | 'invalid' | 1989 |
      | 'physics' | 1899 |

  Scenario Outline: Validate 404 Not Found responses
    Given path '2.1', 'nobelPrize', <category>, <year>
    When method GET
    Then status 404
    And match response.code == '404'
    And match response.message == '#string'

    Examples:
      | category     | year |
      | 'unknown'    | 1989 |
      | 'literature' | 1800 |

  Scenario Outline: Validate 422 Unprocessable Entity responses
    Given path '2.1', 'nobelPrize', <category>, <year>
    When method GET
    Then status 422
    And match response.code == '422'
    And match response.message == '#string'

    Examples:
      | category    | year |
      | 'physics'   | 2023 |
      | 'economics' | 2024 |
